theme: minima
title: Soccer is so awesome!
author: Brijido Ortiz
email: Bortiz4ever@gmail.com
description: > 
 I want to talk about how great soccer is and why it is worth it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
